#volumes:
#  iod_payment_postgres_data:
#  iod_payment_redis_data:

services:
  db:
    container_name: db-payment
    image: postgres:17.2-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME
#    volumes:
#      - iod_payment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USERNAME -d $POSTGRES_DB_NAME" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  redis:
    container_name: redis-payment
    image: redis:7.4.1-alpine
    restart: always
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - ${REDIS_PORT}:6379
#    volumes:
#      - iod_payment_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true