env: "local"
server:
  host: "localhost"
  port: 8081
  timeout: 4s
  idle_timeout: 60s
db:
  postgres:
    host: "localhost"
    username: "postgres"
    password: "postgres"
    db_name: "iod_payment"
    port: 5534
    ssl_mode: "disable"
  redis:
    host: "localhost"
    port: 6379
    password: "12345678"
    protocol: 3
pay_api:
  shop_id: 994351
  secret_key: "test_MheegEXjJUlromDARVVTdiZrsGAB_8YBbgv17erGQ0A"