env: "prod"
server:
  host: "localhost"
  port: 8081
  timeout: 4s
  idle_timeout: 60s
db:
  postgres:
    host: "localhost"
    username: "postgres"
    password: "postgres"
    db_name: "iod_payment"
    port: 5534
    ssl_mode: "disable"
  redis:
    password: "redis_pass"